---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nexabiec/mb-index.nexabie.co.tz/
    - /bin/cp /home/nexabiec/repositories/mb-index/index.php $DEPLOYPATH
    - /bin/cp /home/nexabiec/repositories/mb-index/score.php $DEPLOYPATH
    - /bin/cp /home/nexabiec/repositories/mb-index/Table\ A.pdf $DEPLOYPATH
    - /bin/cp "/home/nexabiec/repositories/mb-index/Gilliam Autism Rating Scale.pdf" $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} \;
    - /bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 {} \;
